#%RAML 0.8
title: Permissions
version: v1
baseUri: http://github.com/org/folio/mod-auth/permissions

documentation:
    title: mod-auth permissions API
    content: This module is responsible for managing and retrieving permissions in the FOLIO system

schemas:
    - permissionUser: !include ../schemas/user.json
    - permissionUserList: !include ../schemas/userList.json

/perms:
    /users:
        get:
            description: Get a list of users
            queryParameters:
                query:
                    description: "A query string to filter users based on matching criteria in fields."
                    required: false
                    type: string
                length:
                    description: "The maximum number of results to return."
                    required: false
                    type: number
                start:
                    description: "The starting index in a list of results (starts at one)."
                    required: false
                    type: number
                hasPermissions:
                    description: "A list of permissions that any returned users must possess."
                    required: false
                    type: string
            responses:
                200:
                    body:
                        application/json:
                            schema: permissionUserList
                400:
                    body:
                        text/plain
                500:
                    body:
                        text/plain
        post:
            description: Add a new user
            body:
                application/json:
                    schema: permissionUser
            responses:
                201:
                    body:
                        application/json:
                            schema: permissionUser
                400:
                    body:
                        text/plain
                500:
                    body:
                        text/plain
        /{username}:
            get:
                description: Get a permission user
                responses:
                    200:
                        body:
                            application/json:
                                schema: permissionUser
                    404:
                        body:
                            text/plain
                    500:
                        body:
                            text/plain
            put:
                description: Modify an existing user
                responses:
                    200:
                        body:
                            application/json:
                                schema: permissionUser
                    400:
                        body:
                            text/plain
                    404:
                        body:
                            text/plain
                    500:
                        body:
                                text/plain
            delete:
                description: Remove a user
                responses:
                    204:
                        body:
                            text/plain
                    404:
                        body:
                            text/plain
                    500:
                        body:
                            text/plain
            /permissions:
                post:
                    description: Add a permission to a user
                    body:
                        text/plain
                    responses:
                        200:
                            body:
                                text/plain
                        400:
                            body:
                                text/plain
                        500:
                            body:
                                text/plain
                /{permissionname}:
                    delete:
                        description: Remove a permission from a user
                        responses:
                            204:
                                body:
                                    text/plain
                            404:
                                body:
                                    text/plain
                            500:
                                body:
                                    text/plain
    /permissions:
        get:
            description: Get a list of existing permissions
            queryParameters:
                query:
                    description: "A query string to filter permissions based on matching criteria in fields."
                    required: false
                    type: string
                length:
                    description: "The maximum number of results to return."
                    required: false
                    type: number
                start:
                    description: "The starting index in a list of results (starts at one)."
                    required: false
                    type: number
                memberOf:
                    description: "A list of permission names that any returned permissions must be a sub-permission of."
                    required: false
                    type: string
                ownedBy:
                    description: "A list of user names that any returned permissions must belong to."
                    required: false
                    type: string

            responses:
                200:
                    body:
                        application/json:
                            schema: permissionListObject
                400:
                    body:
                        text/plain
                500:
                    body:
                        text/plain
        post:
            description: Add a new permission
            body:
                application/json:
                    schema: permission
            responses:
                201:
                    body:
                        application/json:
                            schema:
                                permission
                400:
                    body:
                        text/plain
                500:
                    body:
                        text/plain
        /{permissionname}:
            get:
                description: Get an existing permission by name
                responses:
                    200:
                        body:
                            application/json:
                                schema: permission
                    404:
                        body:
                            text/plain
                    500:
                        body:
                            text/plain
            put:
                description: Modify an existing permission
                body:
                    application/json:
                        schema: permission
                responses:
                    200:
                        body:
                            application/json:
                                schema: permission
                    400:
                        body:
                            text/plain
                    404:
                        body:
                            text/plain
                    500:
                        body:
                            text/plain
            patch:
                description: Modify an existing permission piecemeal
                body:
                    application/json:
                        schema: permission-patch
                responses:
                    200:
                        body:
                            application/json:
                                schema: permission
                    400:
                        body:
                            text/plain
                    404:
                        body:
                            text/plain
                    500:
                        body:
                            text/plain
            delete:
                description: Remove a permission
                responses:
                    204:
                        body:
                            text/plain
                    404:
                        body:
                            text/plain
                    500:
                        body:
                            text/plain

