#%RAML 0.8
title: Permissions
version: v1
baseUri: http://github.com/org/folio/mod-auth/permissions

documentation:
    title: mod-auth permissions API
    content: This module is responsible for managing and retrieving permissions in the FOLIO system

/perms:
    /users:
        get:
            description: Get a list of users
            responses:
                200:
                    body:
                        application/json:
                            schema: permissionUserList
                400:
                    body:
                        text/plain
                500:
                    body:
                        text/plain
        post:
            description: Add a new user
            responses:
                201:
                    body:
                        application/json:
                            schema: permissionUser
                400:
                    body:
                        text/plain
                500:
                    body:
                        text/plain
        /{username}:
            /permissions:
    /permissions:
        /{permissionname}:
            /{subpermissionname}:

