#%RAML 1.0
title: Permissions Interface
version: v1
baseUri: http://github.com/org/folio/mod-auth/_tenantPermissions

documentation:
  - title: tenant permissions API implementation
    content: This API provides a callback point for Okapi when new permission sets are added to the tenant

types:
  okapiPermission.json: !include okapiPermission.json
  okapiPermissionSet: !include okapiPermissionSet.json
  errors: !include raml-util/schemas/errors.schema

traits:
  validate: !include raml-util/traits/validation.raml

/_/tenantpermissions:
  post:
    description: "Load new permissionSets into the permission module when a module gets enabled for a tenant"
    is: [validate]
    body:
      application/json:
        type: okapiPermissionSet
        example: !include raml-util/examples/tenantPermissions.sample
    responses:
      201:
        description: "Permissions loaded successfully"
        body:
          application/json:
            type: okapiPermissionSet
      400:
        description: "Bad request"
        body:
          text/plain:
            example: "Bad request"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Error"

